services:
  - type: web
    name: jobfinders
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT

    envVars:
      - key: PRODUCTION_SQL_DB
        fromDatabase:
          name: jobfinders-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: IS_DEVELOPMENT_SERVER
        value: false
      - key: HOST_ADDRESSES
        fromService:
          type: web
          name: jobfinders
          property: host

databases:
  - name: jobfinders-db
    databaseName: jobfinders
    plan: free