services:
  - type: web
    name: jobfinders
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT

    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PRODUCTION_SQL_DB
        fromDatabase:
          name: jobfinders-db
          property: connectionString
      - key: DEV_SQL_DB
        fromDatabase:
          name: jobfinders-db
          property: connectionString

databases:
  - name: jobfinders-db
    databaseName: jobfinders
    plan: free