from __future__ import annotations
from typing import Optional, List
from pydantic import BaseModel, Field, computed_field, ConfigDict, AwareDatetime
from uuid import uuid4

from src.database.constants import utc_time
from src.database.models.jobs_model import Job


class KeywordSource(BaseModel):
    """
    Where a given keyword came from.  Used to explain
    to recruiters *why* a keyword is important.
    """
    keyword: str
    frequency: int = Field(ge=0, description="Occurrences in source corpus")
    source_type: str = Field(
        description="e.g. 'industry_taxonomy', 'peer_jobs', 'parsed_cvs'"
    )
    weight: float = Field(default=1.0, description="Relative importance (0-1)")


class ATSScoreBreakdown(BaseModel):
    """Granular scoring that feeds the final AI-enhanced ATS score."""
    title_score: int = Field(ge=0, le=100)
    skills_score: int = Field(ge=0, le=100)
    description_score: int = Field(ge=0, le=100)
    formatting_score: int = Field(ge=0, le=100)
    experience_level_score: int = Field(ge=0, le=100)

    @computed_field
    @property
    def total(self) -> int:
        # Weighted average – tweak as needed
        weights = [0.25, 0.30, 0.20, 0.15, 0.10]
        parts = [
            self.title_score,
            self.skills_score,
            self.description_score,
            self.formatting_score,
            self.experience_level_score,
        ]
        return int(round(sum(w * p for w, p in zip(weights, parts))))


class SuggestionImpact(BaseModel):
    """Impact of a single AI suggestion."""
    estimated_score_increase: int = Field(ge=0, le=30)
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str


class AIEnhancementSuggestion(BaseModel):
    """
    A concrete suggestion generated by the AI layer.
    """
    field: str = Field(description="Which job field to change")
    action: str = Field(description="replace / append / delete")
    current: Optional[str] = None
    recommended: Optional[str] = None
    keywords_added: List[str] = Field(default_factory=list)
    impact: SuggestionImpact


class AIATSReport(BaseModel):
    """
    AI-enhanced ATS report that sits *alongside* the legacy ATSReport
    rather than replacing it.  One report per Job.
    """
    id: str = Field(default_factory=lambda: str(uuid4()))
    job_id: str
    generated_at: AwareDatetime = Field(default_factory=utc_time)

    # --- Core analysis ----------------------------------------------------
    score_breakdown: ATSScoreBreakdown
    matched_keywords: List[KeywordSource]
    missing_keywords: List[KeywordSource]

    # --- AI layer ---------------------------------------------------------
    suggestions: List[AIEnhancementSuggestion]

    # --- Meta ------------------------------------------------------------
    keyword_corpora: List[str] = Field(
        description="Which corpora were used (for transparency)"
    )

    @computed_field
    @property
    def ai_enhanced_score(self) -> int:
        """AI-adjusted score (legacy score + predicted uplift)."""
        uplift = sum(s.impact.estimated_score_increase for s in self.suggestions)
        raw = self.score_breakdown.total
        return min(raw + uplift, 100)

    @computed_field
    @property
    def top_5_missing(self) -> List[str]:
        return [
            kw.keyword
            for kw in sorted(
                self.missing_keywords, key=lambda k: k.frequency * k.weight, reverse=True
            )[:5]
        ]

    model_config = ConfigDict(from_attributes=True)
