from routes.fake_data.seeds.fake_job_applications import generate_fake_job_application
from routes.fake_data.seeds.fake_resume import generate_fake_cv
from routes.fake_data.seeds.fake_ats_report import generate_fake_ats_report
